/**
 * @file tkl_watchdog.c
 * @brief this file was auto-generated by tuyaos v&v tools, developer can add implements between BEGIN and END
 *
 * @warning: changes between user 'BEGIN' and 'END' will be keeped when run tuyaos v&v tools
 *           changes in other place will be overwrited and lost
 *
 * @copyright Copyright 2020-2021 Tuya Inc. All Rights Reserved.
 *
 */

// --- BEGIN: user defines and implements ---
#include "tkl_watchdog.h"
#include "tuya_error_code.h"
#include "tkl_adapter.h"

// --- END: user defines and implements ---

/**
 * @brief watchdog init
 *
 * @param[in] cfg: watchdog config
 *
 * @return 0, init error; >0 : the actually watchdog interval
 */

UINT32_T tkl_watchdog_init(TUYA_WDOG_BASE_CFG_T *cfg)
{
    // --- BEGIN: user implements ---
    typedef UINT32_T (*TYPE_T)(TUYA_WDOG_BASE_CFG_T *cfg);

    UINT32_T ret = 0;
    TYPE_T fun;

    fun = (TYPE_T)tkl_adapt_func_get(FUNC_NAME(tkl_watchdog_init));

    if(fun) {
        ret = fun(cfg);
    }

    return ret;
    // --- END: user implements ---
}

/**
 * @brief watchdog deinit
 *
 * @param[in] none
 *
 * @return OPRT_OK on success. Others on error, please refer to tuya_error_code.h
 */

OPERATE_RET tkl_watchdog_deinit(VOID_T)
{
    // --- BEGIN: user implements ---
    typedef OPERATE_RET (*TYPE_T)(VOID_T);

    OPERATE_RET ret = OPRT_NOT_SUPPORTED;
    TYPE_T fun;

    fun = (TYPE_T)tkl_adapt_func_get(FUNC_NAME(tkl_watchdog_deinit));

    if(fun) {
        ret = fun();
    }

    return ret;
    // --- END: user implements ---
}

/**
 * @brief refresh watch dog
 *
 * @param[in] none
 *
 * @return OPRT_OK on success. Others on error, please refer to tuya_error_code.h
 */

OPERATE_RET tkl_watchdog_refresh(VOID_T)
{
    // --- BEGIN: user implements ---
    typedef OPERATE_RET (*TYPE_T)(VOID_T);

    OPERATE_RET ret = OPRT_NOT_SUPPORTED;
    TYPE_T fun;

    fun = (TYPE_T)tkl_adapt_func_get(FUNC_NAME(tkl_watchdog_refresh));

    if(fun) {
        ret = fun();
    }

    return ret;
    // --- END: user implements ---
}

