/**
 * @file tkl_register.c
 * @brief this file was auto-generated by tuyaos v&v tools, developer can add implements between BEGIN and END
 * 
 * @warning: changes between user 'BEGIN' and 'END' will be keeped when run tuyaos v&v tools
 *           changes in other place will be overwrited and lost
 *
 * @copyright Copyright 2020-2021 Tuya Inc. All Rights Reserved.
 * 
 */

// --- BEGIN: user defines and implements ---
#include "tkl_register.h"
#include "tuya_error_code.h"
// --- END: user defines and implements ---

/**
 * @brief read of chip addr
 *
 * @param[in] addr: chip addr 
 *
 * @return return  data of addr
 */
UINT32_T tkl_reg_read(UINT32_T addr)
{
    // --- BEGIN: user implements ---
    return 0;
    // --- END: user implements ---
}

/**
 * @brief bit read
 *
 * @param[in] addr: chip addr 
 *
 * @return return data of bits
 */
UINT32_T tkl_reg_bit_read(UINT32_T addr, TUYA_ADDR_BITS_DEF_E start_bit, TUYA_ADDR_BITS_DEF_E end_bit)
{
    // --- BEGIN: user implements ---
    return 0;
    // --- END: user implements ---
}

/**
 * @brief tuya write of chip addr
 *
 * @param[in] addr :  chip addr
 * @param[in] data: data  , write data
 *
 * @return OPRT_OK on success. Others on error, please refer to tuya_error_code.h
 */
OPERATE_RET tkl_reg_write(UINT32_T addr, UINT32_T data)
{
    // --- BEGIN: user implements ---
    return OPRT_NOT_SUPPORTED;
    // --- END: user implements ---
}

/**
 * @brief bit write of chip addr
 *
 * @param[in] addr : chip addr
 * @param[in] start_bit : start bit to write
 *  @param[in] end_bit  : end bit to write
 *  @param[in] data     : data to write
 *
 * @return OPRT_OK on success. Others on error, please refer to tuya_error_code.h
 */
OPERATE_RET tkl_reg_bit_write(UINT32_T addr, TUYA_ADDR_BITS_DEF_E start_bit, TUYA_ADDR_BITS_DEF_E end_bit, UINT32_T data)
{
    // --- BEGIN: user implements ---
    return OPRT_NOT_SUPPORTED;
    // --- END: user implements ---
}

